build:
    nodes:
        analysis:
            environment:
                php: 8.3.11
            tests:
                override:
                    - php-scrutinizer-run
                    - phpcs-run

filter:
    excluded_paths: [tests/*]

tools:
    external_code_coverage:
        timeout: 5400
        runs: 9
